---
openapi: 3.0.0
info:
  title: Workout Video API
  description: Daddy's workout video api, hell yeah...
  contact:
    email: liam@ometa.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
servers:
  - url: https://virtserver.swaggerhub.com/liammullan/workout-api/1.0.0
    description: SwaggerHub API Auto Mocking
  - url: https://localhost:8080/api
    description: Local context for testing
tags:
  - name: admins
    description: Secured Admin-only calls
  - name: users
    description: Operations available to every user
paths:
  /playlist:
    get:
      tags:
        - users
      summary: generate a workout playlist
      description: by specifying preferences you can get a customised workout playlist
      operationId: createPlaylist
      parameters:
        - name: length
          in: query
          description: length of workout in minutes
          required: true
          style: form
          explode: true
          schema:
            minimum: 5
            type: integer
            format: int32
        - name: activitytype
          in: query
          description: what type of activity e.g. cardio, pilates, yoga
          required: true
          style: form
          explode: true
          schema:
            $ref: '#/components/schemas/ActivityType'
      responses:
        "200":
          description: playlist matching criteria
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Playlist'
        "400":
          description: bad input parameter
        "401":
          $ref: '#/components/responses/UnauthorizedError'
components:
  schemas:
    Playlist:
      type: object
      properties:
        snippets:
          type: array
          items:
            $ref: '#/components/schemas/VideoSnippet'
    ActivityType:
      type: string
      enum:
        - PILATES
        - YOGA
        - HIIT
        - CARDIO
        - STRENGTH
    VideoSnippet:
      required:
        - description
        - end
        - start
        - youtubeid
      type: object
      properties:
        youtubeid:
          type: string
          example: K-PpDkbcNGo
        start:
          description: Start point of video clip in seconds
          minimum: 0
          type: integer
          format: int32
        end:
          description: End of clip from start of video in seconds
          minimum: 0
          type: integer
          format: int32
        description:
          type: string
          example: A brief description of the exercise
  responses:
    UnauthorizedError:
      description: Access token is missing or invalid
  securitySchemes:
    bearerAuth:            # arbitrary name for the security scheme
      type: http
      scheme: bearer
      bearerFormat: JWT    # optional, arbitrary value for documentation purposes
#    openId:   # <--- Arbitrary name for the security scheme. Used to refer to it from elsewhere.
#      type: openIdConnect
#      openIdConnectUrl: https://securetoken.google.com/netlify-and-auth-sandbox/.well-known/openid-configuration
# Apply the security globally to all operations
security:
  - bearerAuth: []         # use the same name as above
    #  - openId: []         # use the same name as above